### ISSUE TITLE
use child_process.spawn instead of execFile

### ISSUE THREAD

**Issue by dumbasPL** [GaspardCulis/node-masscan#1]
> the default stdout 200KB buffer isn't enough and had to be pumped up to 1Gb to avoid the child process being killed

`execFile` keeps a copy of the entire stdout/stderr buffer in memory, but this project doesn't need that as it only reads data as it comes in. By using `spawn` instead, you can run virtually unlimited-size scans without having to allocate an absolutely massive buffer.

also consider using `--output-format ndjson --output-filename - --status-ndjson` to get the data in a machine-readable format. Keep in mind that in this mode masscan doesn't force a flush of the output buffer so you might get multiple results in one flush or partial results aka "cut in half". This is nice for performance as forced buffer flushes are slow but this means that you will have to keep your own (small) buffer that you append to incoming data to and read/pop data from once you have one or more full lines.

**Comment by GaspardCulis** [comment]
Hi, while trying to get masscan outputs when developing this I couldn't find another way to get the masscan outputs live other than not providing output format and output-filename args, but your method works very well. Same for the `spawn` procedure instead of `execFile`, tested it works like a charm. I'm currently migrating the project to TS, and the new npm release will contain your suggestion thx :)

**Comment by GaspardCulis** [comment]
Hi again, did further testing and realized what you meant by `masscan doesn't force a flush of the output buffer`. Idk how to force the reading of the stdout buffer so I'm gonna keep it like it is for now (except for the `spawn` and `execFile` stuff this works like a charm).

**Comment by dumbasPL** [comment]
You essentially have to append the incoming data to a buffer, split the buffer on new lines (because ndjson stands for `New line Delimited JSON`), and then parse and emit any full lines while keeping the remainder of the data for the next time data is read. Also, I've already started working on my own wrapper, will link it here once it's done so you will see what I mean.

Just checked your code, You seem to be using the `exit` event for ending the scan, but the exit event is emitted before the output streams are closed, You most likely want to use the `close` event instead. See the nodejs docks to see what I mean.

**Comment by dumbasPL** [comment]
> will link it here once it's done

https://github.com/dumbasPL/masscan-node

**Comment by GaspardCulis** [comment]
You monster, what a shameless ripoff of my amazing code, you ruined my life I'm out lol

**Comment by dumbasPL** [comment]
> You monster, what a shameless ripoff of my amazing code, you ruined my life I'm out lol

I wish I could prove it (private repo) but the code is about 1 year old, ripped out of one of my old projects. Now I needed it again so decided to make it a package. All I did was add extra parameters on top of the ones I had before and a slight refactor.

**Comment by GaspardCulis** [comment]
Kidding your's is way better than mine, making it public and releasing it on npm makes the world better (if you exclude all the malicious use-cases of this kind of software lol, btw what are you using it for ?).

**Comment by dumbasPL** [comment]
> what are you using it for ?

The obvious answer is scanning the internet. Scanning is not malicious just by itself what you do with the results afterwards might be. but for a more serious answer, I will just respond with your (now removed) readme quote

> I used this code for a copenheimer like project and it hasn't failed me.

same ;)
